apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kibana-operator
  template:
    metadata:
      labels:
        name: kibana-operator
    spec:
      serviceAccountName: kibana-operator
      containers:
        - name: kibana-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - kibana-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kibana-operator"
